import type { Metadata } from "next";
import "./globals.css";
import { poppins } from "./fonts";

export const metadata: Metadata = {
  title: "Best PC: Your trusted partner for personal computers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en text-">
      <body
        className={`${poppins.className}`}
      >
        {children}
      </body>
    </html>
  );
}
